### ISSUE TITLE
NoSuchMethodError, not working on Android 7.1.1

### ISSUE THREAD

**Issue by stemuk** [flutter/posse_gallery#17]
Starting the app via 'flutter run' renders this error message. Tried it multiple times but the App does not seem to start properly on Android 7.1.1.
![265bcc3a-abba-47c9-9dd0-8595691f61b9](https://cloud.githubusercontent.com/assets/17005007/25348871/f936b08e-291f-11e7-89bb-fa84d7621700.jpg)

**Comment by eseidelGoogle** [comment]
This looks like a result of the widget/config rename.  See:https://groups.google.com/forum/#!searchin/flutter-dev/widget$20config%7Csort:relevance/flutter-dev/Lc0KLoKGWSY/SZK77ANtBQAJ

Could you run `flutter analyze` on your project and see if it analyzes cleanly?

**Comment by stemuk** [comment]
Sure: 
'flutter analyze' returns "error • Undefined name 'config' at lib/main.dart:80:25 • undefined_identifier"
1 issue found.

**Comment by eseidelGoogle** [comment]
Oh, sorry.  I just haven't updated this app.  Others are doing active development on this repository, but in the `development` branch.

**Comment by stemuk** [comment]
My bad, the development branch works great, should have checked out the latest branch first. Pretty cool app btw! :D
